//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JapaneseEraClassLibrary.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
                  {
                  ""JapaneseEraTable"":[
                  {""startDate"":""2019-05-01"",""Name"":""元新"",""EnglishName"":""Genshin""},
                  {""startDate"":""1989-01-08"",""Name"":""平成"",""EnglishName"":""Heisei""},
                  {""startDate"":""1926-12-25"",""Name"":""昭和"",""EnglishName"":""Showa""},
                  {""startDate"":""1912-07-30"",""Name"":""大正"",""EnglishName"":""Taisho""},
                  {""startDate"":""1868-01-25"",""Name"":""明治"",""EnglishName"":""Meiji""}
                  ]
                  }
                ")]
        public string JapaneseEraTable {
            get {
                return ((string)(this["JapaneseEraTable"]));
            }
            set {
                this["JapaneseEraTable"] = value;
            }
        }
    }
}
